apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: yvonnelu/backend-backend:latest
        ports:
        - containerPort: 3001
        env:
        - name: DATABASE_NAME
          value: "period-tracker"
        - name: DATABASE_URI
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DATABASE_URI
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: JWT_SECRET
        - name: PORT
          value: "3001"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
  type: ClusterIP