services:
  backend:
    container_name: backend-service
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_URI: ${DATABASE_URI}
      JWT_SECRET: secretKey
    ports:
      - '3001:3001'
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
